### ISSUE TITLE
Should reveal be called witness?

### ISSUE THREAD

**Issue by rehno-lindeque** [circuithub/haskell-access#4]
I.e. `witness` corresponds to the same concept in `Data.Tagged`

**Comment by TheunisKotze** [comment]
Just my personal opinion, reveal seems much less ambiguous/confusing to me

**Comment by rehno-lindeque** [comment]
I agree. I was already a bit reluctant to do this to start with because I was calling the value level argument being passed in the "witness" to the type guarding the secret.

Also, `Data.Tagged` and `Data.Private` are different types with a purpose.
